include=/home/jialuo/.config/fuzzel/themes/noctalia

;----------全局设置-----------
;字体
font=STZhongsong
;图标主题
icon-theme=Tela
width=30
use-bold=false

[border]
width=3

;---------作为启动器----------
[main]
line-height=19
lines=13
;输入框与下方的间隔
inner-pad=5
;输入框文字
placeholder="海日生长夜"
;匹配计数器
match-counter=no 
;---------管道启动------------
;[dmenu]
