color0 #091517
color1 #ffb4ab
color2 #77daa0
color3 #93d5aa
color4 #82d3e0
color5 #77daa0
color6 #93d5aa
color7 #d7e5e7
color8 #7c959a
color9 #ffb4ab
color10 #77daa0
color11 #93d5aa
color12 #82d3e0
color13 #77daa0
color14 #93d5aa
color15 #d7e5e7

cursor                #d7e5e7
cursor_text_color     #091517
background            #091517
foreground            #d7e5e7
selection_foreground  #b1cbd0
selection_background  #334b4f
active_border_color   #77daa0
inactive_border_color #334b4f
url_color             #77daa0
