color0 #0e141c
color1 #ffb4ab
color2 #4ed8e9
color3 #81d3df
color4 #a4c9fe
color5 #4ed8e9
color6 #81d3df
color7 #dee2ee
color8 #8691a4
color9 #ffb4ab
color10 #4ed8e9
color11 #81d3df
color12 #a4c9fe
color13 #4ed8e9
color14 #81d3df
color15 #dee2ee

cursor                #dee2ee
cursor_text_color     #0e141c
background            #0e141c
foreground            #dee2ee
selection_foreground  #bcc7db
selection_background  #3d4758
active_border_color   #4ed8e9
inactive_border_color #3d4758
url_color             #4ed8e9
