color0 #0a1519
color1 #ffb4ab
color2 #61dbb8
color3 #88d6bb
color4 #88d1ec
color5 #61dbb8
color6 #88d6bb
color7 #d9e4ea
color8 #7e949e
color9 #ffb4ab
color10 #61dbb8
color11 #88d6bb
color12 #88d1ec
color13 #61dbb8
color14 #88d6bb
color15 #d9e4ea

cursor                #d9e4ea
cursor_text_color     #0a1519
background            #0a1519
foreground            #d9e4ea
selection_foreground  #b3cad4
selection_background  #344a52
active_border_color   #61dbb8
inactive_border_color #344a52
url_color             #61dbb8
