#kde桌面使用的kitty终端配置文件


include ~/.config/kitty/themes/1684 Dark.conf

clipboard_control write-clipboard read-clipboard


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

background_opacity 1.00
#光标尾迹
cursor_trail 1
# cursor_trail_color none
