#niri桌面使用的kitty配置文件，位于~/.config/kitty/kitty.conf

# BEGIN_KITTY_THEME
# Noctalia
include ~/.config/kitty/themes/noctalia.conf
# END_KITTY_THEME

clipboard_control write-clipboard read-clipboard


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

background_opacity 1.00
#光标尾迹
cursor_trail 1
# cursor_trail_color none
#允许远程控制
allow_remote_control yes
#指定监听方式
listen_on unix:/tmp/nirikitty-none
